"""Type stubs for the native Rust extension module."""

class Location:
    """A point on the screen with x, y coordinates."""

    x: int
    y: int

    def __init__(self, x: int, y: int) -> None: ...
    def offset(self, offset: Offset) -> Location: ...
    def distance_to(self, other: Location) -> float: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class Offset:
    """A relative displacement with dx, dy components."""

    dx: int
    dy: int

    def __init__(self, dx: int, dy: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class Region:
    """A rectangular area on the screen."""

    x: int
    y: int
    w: int
    h: int

    def __init__(self, x: int, y: int, w: int, h: int) -> None: ...
    def center(self) -> Location: ...
    def contains(self, loc: Location) -> bool: ...
    def area(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
